### ISSUE TITLE
Gripper opening is inverted with fake server

### ISSUE THREAD

**Issue by FabienDanieau** [pollen-robotics/reachy2_sdk_server#102]
discussed here https://github.com/pollen-robotics/reachy2_sdk_server/pull/80

open/close is inverted for left arm
close lead to weird value for right arm

**Comment by RemiFabre** [comment]
Closing because its a duplicate of this issue:
https://github.com/pollen-robotics/reachy2_sdk_server/issues/79

To be confirmed but this might be fixed with the new grippers (that are once again symmetric IRL) when I push the update to the gripper controller.
